### ISSUE TITLE
[TASK] Improve the extension loading

### ISSUE THREAD

**Issue by CermakM** [CermakM/jupyter-require#8]
**User story**
As a Jupyter Require user,
I want to wait for the extension to be loaded and I want to require it as a module
so that I could make use of it in my application.

**Additional context**
The current loading produces an annoying error:

```
Exception ignored in: <bound method Comm.__del__ of <ipykernel.comm.comm.Comm object at 0x7fbebc787128>>
Traceback (most recent call last):
  File "/home/macermak/.local/share/virtualenvs/jupyter-nbrequirements-UeYIcNmZ/lib/python3.6/site-packages/ipykernel/comm/comm.py", line 76, in __del__
    self.close()
  File "/home/macermak/.local/share/virtualenvs/jupyter-nbrequirements-UeYIcNmZ/lib/python3.6/site-packages/ipykernel/comm/comm.py", line 116, in close
    self.kernel.comm_manager.unregister_comm(self)
  File "/home/macermak/.local/share/virtualenvs/jupyter-nbrequirements-UeYIcNmZ/lib/python3.6/site-packages/ipykernel/comm/manager.py", line 56, in unregister_comm
    comm = self.comms.pop(comm.comm_id)
KeyError: ('communicate.JupyterRequire#1569583585528',)
```

**Comment by CermakM** [comment]
Fixed in https://github.com/CermakM/jupyter-require/commit/96de78f1848a6b8c45653e2895743c35693fc21e
